import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Головна вступна сторінка (вже є з шаблону: docs/intro.md)
    'intro',

    // API розділ
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        // Огляд API (створимо файл нижче)
        'api/overview',

        {
          type: 'category',
          label: 'Tasks API',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/tasks', // бере все з docs/api/tasks
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
