import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Main intro page
    'intro',

    // API Section
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        'api/overview',
        {
          type: 'category',
          label: 'API reference',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/reference', // takes everything from docs/api/reference
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
